services:
  - type: web
    name: tg-video-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app & python keepalive.py
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here
      - key: ADMIN_IDS
        value: "your_admin_id_here"
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: tg-video-downloader
          type: web
          property: url